version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=covid_portal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  web:
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/covid_portal
      - DJANGO_ENV=development
    build: .
    expose:
      - "8000"
    command: ./entrypoint.sh
    depends_on:
      - db
    volumes:
      - .:/code
  nginx:
    build: ./config/nginx
    volumes:
      - .:/code
    ports: 
      - 8000:80
    depends_on:
      - web

volumes:
  static_volume: